import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  placeholder: {
    fontSize: 13,
  },
  applicantMain: {
    width: "auto",
    height: 120,
    // flexDirection: "column",
    // columnGap: 15,
    // justifyContent: "center",
    // alignContent: "center",
    // alignSelf: "center",
    display: "flex",
    marginBottom: 40,
    borderWidth: 1,
    flex: 1,
    borderColor: "blue",
  },
  imageProfile: {
    resizeMode: "cover",
    borderRadius: 50,
    width: 100,
    height: 100,
    // alignContent: "center",
    alignSelf: "center",
    // flex: 1,
    display: "flex",
    marginBottom: 6,
  },
  applicantdetails: {
    // flex: 2,
    display: "flex",
  },
  applicantName: {
    fontSize: 19,
    textTransform: "capitalize",
    top: 3,
  },
  applicantRole: {
    fontSize: 14,
    textTransform: "uppercase",
  },
  applicantContacts: {
    fontSize: 14,
  },
  skillsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    display: "flex",
    // marginBottom: 20,
  },
  skillsList: {
    // backgroundColor: "#F8F9FA",
    backgroundColor: "#EDEDED",
    borderRadius: 20,
    marginHorizontal: 5,
    marginVertical: 5,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  text: {
    textTransform: "uppercase",
    color: "#606060",
    fontSize: 15,
  },
  filesContainer: {
    display: "flex",
    paddingBottom: 150,
  },
  fileText: {
    fontSize: 17,
    textTransform: "uppercase",
  },
  choosefileContainer: {
    borderBottomWidth: 2,
    borderColor: "black",
    flexDirection: "row",
    columnGap: 12,
    borderRightWidth: 0,
    borderTopWidth: 0,
    marginVertical: 5,
    marginBottom: 15,
    // flex: 1,
    display: "flex",
  },
  downloadBtn: {
    paddingHorizontal: 15,
    height: 32,
    backgroundColor: "black",
    // alignItems: "center",
    justifyContent: "center",
  },
  viewPortfolio: {
    position: "absolute",
    top: 30,
    paddingHorizontal: 35,
    height: 45,
    backgroundColor: "black",
    // alignItems: "center",
    justifyContent: "center",
  },
  btnStyle: {
    fontSize: 15,
    color: "white",
  },
  fileNamePlaceholder: {
    marginTop: 6,
  },
  imageStyle: {
    resizeMode: "contain",
    borderRadius: 5,
    // width: 320,
    // height: 180,
  },
  imageContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 10,
    display: "flex",
    // marginBottom: 40,
    marginTop: 100,
  },
  buttonContainer: {
    top: 40,
    height: 90,
  },
  buttonStyle: {
    color: "white",
    fontSize: 18,
    textTransform: "uppercase",
    marginBottom: 30,
    // marginLeft: 220,
    paddingTop: 10,
    paddingLeft: 20,
    // paddingRight: 20,
    paddingBottom: 10,
    alignSelf: "center",
    backgroundColor: "black",
  },
});
