import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  btnContainer: {
    backgroundColor: "#373737",
    height: 40,
    width: "auto",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
  },
  btnText: {
    color: "white",
    fontFamily: "Montserrat-Regular",
    fontSize: 20,
    textAlign: "center",
    textTransform: "capitalize",
  },
  btnPrimary: {
    backgroundColor: "#373737",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 20,
    flex: 0,
    textWrap: "wrap",
    borderRadius: 5,
  },
  btnSecondary: {
    backgroundColor: "#121212",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 20,
    flex: 0,
    textWrap: "wrap",
    borderRadius: 5,
  },
  btnTertiaryLight: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#000",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 20,
    flex: 0,
    textWrap: "wrap",
    borderRadius: 30,
  },

  btnTertiaryDark: {
    backgroundColor: "#000",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 20,
    flex: 0,
    textWrap: "wrap",
    borderRadius: 30,
  },
});
